spring.application.name=banco-digital

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/banco2026}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secreto=BancoDigital2026ClaveSecretaSuperSeguraParaFirmarTokensJWTHS256
jwt.expiracion-access-ms=600000
jwt.expiracion-refresh-dias=7

server.port=${PORT:8080}