apiVersion: v1
kind: Secret
metadata:
  name: banco-digital-secret
  namespace: banco-digital
type: Opaque
stringData:
  DB_PASS: "Bancoudea123"
  JWT_SECRET: "BancoDigital2026ClaveSecretaSuperSeguraParaFirmarTokensJWTHS256"
  GATEWAY_SECRET: "clave_secreta_pasarela_banco_2026_hmac"
  POSTGRES_PASSWORD: "Bancoudea123"
