{
 "title": "Banco Digital Backend - Observabilidad Sprint 3",
 "tags": [
  "spring-boot",
  "banco-digital",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Backend UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"banco-digital-backend\"}"
    }
   ]
  },
  {
   "title": "Peticiones HTTP por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Memoria JVM usada",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes)" }
   ]
  }
 ]
}